# Site Details

title: Samuel Kent
author: Samuel Kent
url: "https://SamTheDude.github.io"

# --- Social Media ---
# My pages
social-network-links:
  email: kent_sam@outlook.com
  github: SamTheDude
  linkedin: kent-samuel

# --- Site Formatting ---
url-pretty: "SamTheDude.github.io"

# Favicon
favicon-location: "/assets/images/favicon.png"

# Navbar
#navbar-links:


# Posts
excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true
date_format: "%B %-d, %Y"

# Site colours
navbar-col: "#A04A58"
navbar-text-col: "#FFFFFF"
navbar-border-col: "#EDCCC3"
page-col: "#000000"
text-col: "#F3F4EE"
link-col: "#EBEAD9"
hover-col: "#C6C6C6"
footer-col: "#000000"
footer-border-col: "#090909"
footer-text-col: "#F3F4EE"
footer-link-col: "#D47D8B"

# Remove Beautiful Jekyll ad
remove-ads: true

# --- Build settings ---
# Theme Setup
remote_theme: daattali/beautiful-jekyll@5.0.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Exclude files from Jekyll build.
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/